const Discord = require('discord.js');

exports.get = () => {
    let manytags = [
        "ПРА-ВО",
        "АШ",
        "ЦБ",
        
        "LSPD",
        "ЛСПД",
        "SFPD",
        "СФПД",
        "LVPD",
        "ЛВПД",
        "RCPD",
        "РКПД",
        "RCSD",
        "РКШД",
        
        "LSA",
        "ЛСА",
        "SFA",
        "СФА",
        "LSA",
        "ЛСА",
        "SFA",
        "СФА",
        "ТСР",
        "ТЮРЬМА",
        
        "LSMC",
        "ЛСМЦ",
        "SFMC",
        "СФМЦ",
        "LVMC",
        "ЛВМЦ",
        "БЛС",
        "BLS",
        "БСФ",
        "BSF",
        "БЛВ",
        "BLV",
        
        "СМИ ЛС",
        "СМИ ЛВ",
        "СМИ СФ",
        
        "WMC",
        "RM",
        "РМ",
        "LCN",
        "ЛКН",
        "YAKUZA",
        "ЯКУДЗА",
        
        "GROVE",
        "ГРУВ",
        "BALLAS",
        "БАЛЛАС",
        "VAGOS",
        "ВАГОС",
        "AZTEC",  
        "АЦТЕК",
        "RIFA",
        "РИФА",
        "NW",
        "НВ",
    ];
    return manytags;
}
